language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - nosetests -v --with-coverage --cover-package=ir_profile_tracker