os: linux
dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codeclimate-test-reporter

script:
  - nosetests -v --with-coverage --cover-package=ir_profile_tracker --cover-package=main

after_success:
  - codeclimate-test-reporter